/*
Copyright 2025 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import "k8s.io/apimachinery/pkg/runtime"

// addDefaultingFuncs registers defaulting functions for v1alpha1 types.
// RegisterDefaults is generated by defaulter-gen in zz_generated.defaults.go.
func addDefaultingFuncs(scheme *runtime.Scheme) error {
	return RegisterDefaults(scheme)
}

// SetDefaults_DeviceMetadata sets defaults for DeviceMetadata.
// Currently a no-op since all fields are explicitly set by the framework.
// Future versions may add defaulting logic here.
func SetDefaults_DeviceMetadata(in *DeviceMetadata) {
}
